### ISSUE TITLE
install on mac os, R 3.6.1

### ISSUE THREAD

**Issue by Gu2uMo** [KasperSkytte/mmgenome2#32]
done as the website https://kasperskytte.github.io/mmgenome2/articles/MACinstall.html
1. while an error at the 4th step  
run: `brew install gcc --without-multilib `
--without-multilib would raise an error and i delete it 
the gcc installed is version 9, so I change 7 with 9 in the file Makevars

2. Then I open R with sudo open -a R, do as the guide:

`>remotes::install_github("kasperskytte/mmgenome2")`
Downloading GitHub repo kasperskytte/mmgenome2@master
Skipping 6 packages ahead of CRAN: Biostrings, BiocGenerics, S4Vectors, IRanges, XVector, zlibbioc
Running `R CMD build`...
* checking for file ‘/private/var/folders/q_/3k0tthbx72jdw_7jy701dtl00000gn/T/Rtmpb5HQ0i/remotes256a7b8c0a21/KasperSkytte-mmgenome2-7b48038/DESCRIPTION’ ... OK
* preparing ‘mmgenome2’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘mmgenome2_2.1.tar.gz’
* installing *source* package ‘mmgenome2’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Note: wrong number of arguments to 'sqrt' 
Note: wrong number of arguments to 'floor' 
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mmgenome2)

`>library(mmgenome2)`
Error: package or namespace load failed for ‘mmgenome2’:
 .onAttach failed in attachNamespace() for 'mmgenome2', details:
  call: fun(libname, pkgname)
  error: object 'remote_version' not found
In addition: Warning message:
In file(con, "r") :
  URL 'https://raw.githubusercontent.com/kasperskytte/mmgenome2/master/DESCRIPTION': status was 'Couldn't connect to server'

while the installation is done, but i can't library it.
could anyone give some help?
Thanks.

**Comment by KasperSkytte** [comment]
Hi there

I'm sorry for your trouble, I am on paternity leave until 23 march, so can't provide full support until then. But I can see that it's due to the changes I made to .onAttach() in https://github.com/KasperSkytte/mmgenome2/blob/master/R/zzz.R#L25 when it checks for newest version on load, it's not mac specific. So it fails doing that because you couldn't connect to the github server for whatever reason. Can you try making sure you are connected to the internet and that the following works? `DESCRIPTION <- readLines(“https://raw.githubusercontent.com/kasperskytte/mmgenome2/master/DESCRIPTION”)`

Otherwise, until I get back paternity leave, if you fork the repository, delete the zzz.R file, and then try installing again from your own repo, it should work fine.

**Comment by KasperSkytte** [comment]
Fixed in https://github.com/KasperSkytte/mmgenome2/commit/cd86b70567dcce6ac63d088ee7b0eeb764c63728
